name: build-android-apk

on:
  push:
    branches: [main, master]
  workflow_dispatch: {}

jobs:
  export-android:
    name: Android Export
    runs-on: ubuntu-22.04
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Godot export templates
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/4.3.stable ~/.local/share/godot/export_templates/4.3.stable
          echo 'export/android/java_sdk_path = "/usr/lib/jvm/java-17-openjdk-amd64"' >> ~/.config/godot/editor_settings-4.3.tres

      - name: Create build directory
        run: mkdir -v -p build

      - name: Android debug build
        run: |
          godot --headless --verbose --export-debug "Android" build/nextbot-school.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: nextbot-school-apk
          path: build/nextbot-school.apk
